server:
  port: ${PORT:5001}

base-url: /api

springdoc:
  swagger-ui:
    path: /swagger.html

spring:
  application:
    name: app

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop