server:
  error:
    include-stacktrace: never

springdoc:
  swagger-ui:
    path: /swagger.html

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO
